### ISSUE TITLE
Android Demo 好多 crash

### ISSUE THREAD

**Issue by Ydcool** [leancloud/leanmessage-demo#38]
点击某条消息进入单聊的时候，下拉刷新会触发NullPointerException:
```xml
03-15 09:03:58.503 19423-19423/com.leancloud.im.guide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.leancloud.im.guide, PID: 19423
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.leancloud.im.guide/com.leancloud.im.guide.activity.AVSquareActivity}: java.lang.NullPointerException
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2469)
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: java.lang.NullPointerException
                                                                            at com.leancloud.im.guide.activity.AVSquareActivity.getSquare(AVSquareActivity.java:93)
                                                                            at com.leancloud.im.guide.activity.AVSquareActivity.onCreate(AVSquareActivity.java:63)
                                                                            at android.app.Activity.performCreate(Activity.java:5310)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2469) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 

```

--- 
有时是这种
```xml
03-15 09:06:54.071 21028-21028/com.leancloud.im.guide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.leancloud.im.guide, PID: 21028
                                                                        java.lang.NullPointerException
                                                                            at com.leancloud.im.guide.fragment.ChatFragment$1.onRefresh(ChatFragment.java:70)
                                                                            at android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:185)
                                                                            at android.support.v4.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
                                                                            at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:5541)
                                                                            at android.view.View.draw(View.java:14687)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3099)
                                                                            at android.view.View.draw(View.java:14779)
                                                                            at android.view.View.getDisplayList(View.java:13615)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.getDisplayList(View.java:13607)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.getDisplayList(View.java:13607)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.draw(View.java:14779)
                                                                            at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                            at android.view.View.getDisplayList(View.java:13615)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.getDisplayList(View.java:13607)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.getDisplayList(View.java:13607)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at android.view.View.getDisplayList(View.java:13607)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.View.draw(View.java:14470)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2418)
                                                                            at android.view.View.draw(View.java:14779)
                                                                            at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2398)
                                                                            at android.view.View.getDisplayList(View.java:13615)
                                                                            at android.view.View.getDisplayList(View.java:13662)
                                                                            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1663)
                                                                            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1538)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2775)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2637)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2253)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1210)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:610)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:578)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:793)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                        	at java.lang.re

```

**Comment by daweibayu** [comment]
#39  已经修复了，可以试一下。
如还有其他问题请反馈，我们会及时修复。
