### ISSUE TITLE
web app 调试失败

### ISSUE THREAD

**Issue by triphoon** [leancloud/leanmessage-demo#46]
/XX/leanmessage-demo-master/Web/gulp_tasks/karma.js:10
  return failCount => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module._load (/XX/leanmessage-demo-master/Web/node_modules/gulp-hub/lib/load-subfile.js:26:32)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/XX/leanmessage-demo-master/Web/node_modules/gulp-hub/lib/load-subfile.js:30:4)
    at /XX/leanmessage-demo-master/Web/node_modules/gulp-hub/lib/hub-registry.js:57:30
    at arrayEach (/XX/leanmessage-demo-master/Web/node_modules/gulp-hub/node_modules/lodash/index.js:1289:13)

npm ERR! @ build: `gulp`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 16.0.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /XX/leanmessage-demo-master/Web
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /XX/leanmessage-demo-master/Web/npm-debug.log
npm ERR! not ok code 0

**Comment by triphoon** [comment]
nodejs版本不对
