### ISSUE TITLE
点击录音会crash

### ISSUE THREAD

**Issue by jesse920524** [leancloud/leanmessage-demo#52]
05-24 14:42:47.610 14811-14811/com.example.admin.leancloudimtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.admin.leancloudimtest, PID: 14811
                                                                                   java.lang.RuntimeException: setAudioSource failed.
                                                                                       at android.media.MediaRecorder.setAudioSource(Native Method)
                                                                                       at cn.leancloud.chatkit.view.LCIMRecordButton.startRecording(LCIMRecordButton.java:198)
                                                                                       at cn.leancloud.chatkit.view.LCIMRecordButton.startRecord(LCIMRecordButton.java:140)
                                                                                       at cn.leancloud.chatkit.view.LCIMRecordButton.onTouchEvent(LCIMRecordButton.java:96)
                                                                                       at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                       at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                                   	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRoot

**Comment by daweibayu** [comment]
Android 可以试用 https://github.com/leancloud/LeanCloudChatKit-Android ，这个 demo 不再做后续支持。
